
person:
  lastName: 张三${random.int(10)}
  age: 20
  boss: false
  birth: 2017/10/12
  dog:
    name: xiaogou
    age: 2
  maps: {'k1': v1,'k2': v2}
  lists: ['list1','list2','list3']

---
spring:
  profiles:
    active: dev #profiles.active：激活指定配置

---

spring:
  profiles: prod
server:
  port: 8088

---
spring:
  profiles: default #profiles: default表示未指定时的默认配置
server:
  port: 8089

---
spring:
  profiles: dev
server:
  port: 8090